server:
  port: 8022


spring:
  zipkin:
    base-url: http://localhost:9016
    sender:
      type: web
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.jdbc.Driver


